services:
  - type: web
    name: license-plate-system
    env: python
    region: singapore
    plan: free
    rootDir: license_plate_system
    buildCommand: pip install -r ../requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn license_plate_system.wsgi:application --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: license-plate-system.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: license-plate-db
          property: connectionString

databases:
  - name: license-plate-db
    plan: free
    databaseName: license_plate_db
    user: license_plate_user

